# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4094963eeaf5198d3ebf72f93bb31f88724d133eb580cfc4b0b5ccae1a32315214b18b1832c192f28287633919b0b8a8ed9563aded64e0eaca684bf7abedcbb

test:
  secret_key_base: 3f13c41bb6a50436ae18438ba9d5ae9d771283427a30c47766ab92f5ff91b265ea6f14adf122cc0a2695159807cc7f20116e881330f1662751c026c5f77a20c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
